---
'centos-64-x64':
  facts:
    kernelrelease: "2.6.32-358.el6.x86_64"
    operatingsystem: CentOS
    kernelmajversion: "2.6"
    architecture: x86_64
    facterversion: "1.6.18"
    kernelversion: "2.6.32"
    operatingsystemrelease: "6.4"
    osfamily: RedHat
    kernel: Linux
    rubyversion: "1.8.7"
  provider_specifics:
    vagrant:
      box: 'centos-64-x64'
      box_url: 'http://radon.usersys.redhat.com/templates/boxes/centos-64-x64.box'
'ubuntu-server-12042-x64':
  facts:
    kernel: Linux
    architecture: amd64
    operatingsystem: Ubuntu
    lsbdistid: Ubuntu
    facterversion: "1.6.17"
    kernelmajversion: "3.2"
    kernelrelease: "3.2.0-29-generic"
    kernelversion: "3.2.0"
    lsbdistcodename: precise
    lsbdistdescription: "Ubuntu 12.04.1 LTS"
    lsbdistrelease: "12.04"
    lsbmajdistrelease: "12"
    operatingsystemrelease: "12.04"
    osfamily: Debian
    rubyversion: "1.9.2"
  provider_specifics:
    vagrant:
      box: 'ubuntu-server-12042-x64'
      box_url: 'http://radon.usersys.redhat.com/templates/boxes/ubuntu-server-12042-x64.box'
'debian-70-x64':
  facts:
    architecture: amd64
    kernel: Linux
    operatingsystem: Debian
    lsbdistid: Debian
    facterversion: "1.6.18"
    kernelmajversion: "3.2"
    kernelrelease: "3.2.0-4-amd64"
    kernelversion: "3.2.0"
    lsbdistcodename: wheezy
    lsbdistdescription: "Debian GNU/Linux 7.0 (wheezy)"
    lsbdistrelease: "7.0"
    lsbmajdistrelease: "7"
    operatingsystemrelease: "7.0"
    osfamily: Debian
    rubyversion: "1.9.3"
  provider_specifics:
    vagrant:
      box: 'debian-70-x64'
      box_url: 'http://radon.usersys.redhat.com/templates/boxes/debian-70-x64.box'
'debian-607-x64':
  facts:
    kernel: Linux
    lsbmajdistrelease: "6"
    operatingsystemrelease: "6.0.7"
    kernelrelease: "2.6.32-5-amd64"
    osfamily: Debian
    lsbdistrelease: "6.0.7"
    lsbdistcodename: squeeze
    lsbdistdescription: "Debian GNU/Linux 6.0.7 (squeeze)"
    kernelversion: "2.6.32"
    operatingsystem: Debian
    kernelmajversion: "2.6"
    facterversion: "1.6.18"
    rubyversion: "1.8.7"
    lsbdistid: Debian
    architecture: amd64
  provider_specifics:
    vagrant:
      box: 'debian-607-x64'
      box_url: 'http://radon.usersys.redhat.com/templates/boxes/debian-607-x64.box'
